#!/bin/bash

# This is used to enable the <TAB> auto-complete functionality

src="$HOME/Documents/commands/open.txt"
readonly src

wordlist=$(cat "$src")
readonly wordlist

complete -W "$wordlist" open
