### Playbook Configuration Variables
# You may modify the following variables to customize the playbook to your
# specific needs, however do not remove any variables, they are all required
# for the playbook to function.

## User info
username: saief1999

dotfiles_path: utility-scripts/dotfiles
