---
- name: Check if yay is installed
  command:
    cmd: pacman -Q yay
  register: yay_check
  ignore_errors: true

- name: Clone yay PKGBUILD
  command:
    cmd: "git clone https://aur.archlinux.org/yay.git yay"
    chdir: "~{{ username }}"
    creates: "~{{ username }}/yay"
  become: true
  become_user: "{{ username }}"

- name: Install yay if needed
  command:
    cmd: makepkg -si
    chdir: "~{{ username }}/yay"
  when: yay_check.stdout.find('was not found') != 0
  become: true
  become_user: "{{ username }}"

- name: Download XDG dirs
  pacman:
    name:
      - xdg-user-dirs

- name: Setup XDG dirs
  command:
    cmd: xdg-user-dirs-update
    creates: "~{{ username }}/Documents"
  become: true
  become_user: "{{ username }}"

- name: Install Network Applet
  pacman:
    name:
      - network-manager-applet

- name: Install Whisker Menu
  pacman:
    name:
      - xfce4-whiskermenu-plugin

- name: Install Audio Utilities
  pacman:
    name:
      - pulseaudio
      - pulseaudio-bluetooth
      - pulseaudio-jack
      - pavucontrol
      - alsa-firmware
      - alsa-utils

- name: Install volman to auto mount disks with thunar
  pacman:
    name:
      - thunar-volman
      - gvfs

- name: Install Archive utility for XFCE
  pacman:
    name:
      - thunar-archive-plugin
